"""user img column

Revision ID: bef0c0fd6f24
Revises: 0e63e2ab39f0
Create Date: 2024-06-29 17:24:02.411843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef0c0fd6f24'
down_revision: Union[str, None] = '0e63e2ab39f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    # ### end Alembic commands ###
